export const DAYS_BEFORE_AFTER_FLIGHT_DATE = 10;
export const EUR_USD_COEFF = 1.1;
export const EUR_RUB_COEFF = 85.78;
export const EUR_PLN_COEFF = 4.57;
export const MINIMUM_SEATS_NUMBER = 150;
export const MAXIMUM_SEATS_NUMBER = 350;
export const NO_SEATS_CHANCE = 6; // 1 out of 6
export const MINIMUM_ADULT_FARE = 200; // in EUR
export const MAXIMUM_ADULT_FARE = 300;
export const MINIMUM_CHILD_FARE = 100;
export const MAXIMUM_CHILD_FARE = 199;
export const MINIMUM_INFANT_FARE = 50;
export const MAXIMUM_INFANT_FARE = 99;
export const FLIGHT_PRICE_DECIMAL_PLACES = 2;
export const MIN_FLIGHT_DURATION = 60; // in minutes
export const MAX_FLIGHT_DURATION = 360;
export const ROUND_TO_MINUTES = 5; // round a Date() to the nearest 5 minutes
export const MINIMUM_ADDITIONAL_ARRIVAL_DELAY = 15; // in minutes
export const MAXIMUM_ADDITIONAL_ARRIVAL_DELAY = 30; // in minutes
export const MAXIMUM_AIRPORT_CONNECTIONS = 2;
export const AIRPORT_CONNECTIONS_CHANCE = 6; // 1 out of 6
export const DAYS_BEFORE_AFTER_FLIGHT = 10;
